### ISSUE TITLE
AttributeError: 'RoomResponseEstimator' object has no attribute 'test_pulse'

### ISSUE THREAD

**Issue by tballast** [baranovmv/RoomResponse#1]
Line 38 in evaluation.py attempt to access the member "test_pulse" in the RoomResponseEstimator class object but it is not defined. 

`estimator = RoomResponseEstimator()`
...
`in_sig = np.append(in_sig, sig_env.run(estimator.test_pulse))`

Where should this be coming from?

**Comment by baranovmv** [comment]
> Where should this be coming from?

It should be ```estimator.probe_pulse``` of course! Thank you, I've fixed in  7ed8f24db9349902aa660264b9ae7ab818d645db

Beware, I've changed the author in several commits (I accidentally mentioned my work email), so please do ```git pull --rebase origin```
